.ALIASES
M_M1            M1(d=OUT g=IN s=N00115 s=N00115 ) CN @NOT_22.SCHEMATIC1(sch_1):INS32@PTM_MODELS.pMOS_22nm_PTM.Normal(chips)
M_M2            M2(d=OUT g=IN s=0 s=0 ) CN @NOT_22.SCHEMATIC1(sch_1):INS73@PTM_MODELS.nMOS_22nm_PTM.Normal(chips)
C_C1            C1(1=0 2=OUT ) CN @NOT_22.SCHEMATIC1(sch_1):INS181@ANALOG.C.Normal(chips)
V_A             A(+=IN -=0 ) CN @NOT_22.SCHEMATIC1(sch_1):INS2309@SOURCE.VPULSE.Normal(chips)
V_Vin           Vin(+=N00115 -=0 ) CN @NOT_22.SCHEMATIC1(sch_1):INS2409@SOURCE.VDC.Normal(chips)
_    _(IN=IN)
_    _(OUT=OUT)
.ENDALIASES
